services:
  mysql:
    image: mysql:latest
    container_name: interactive-cv-2-be
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: interactivecv2
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # uncomment when final release to containerize all in Docker
  # interactivecv:
  #   image: interactivecv
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 8080:8080
volumes:
  mysql_data:
